## LU Factorization with Partial Pivoting

Reference: [Advanced Linear Algebra: Foundations to Frontiers - Week 5 The LU and Cholesky Factorizations](https://www.cs.utexas.edu/users/flame/laff/alaff/chapter05-LU-factorization.html)

### SciPy Implementation

Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html#scipy.linalg.lu

> Compute LU decomposition of a matrix with partial pivoting.
> 
> The decomposition satisfies:
> 
> `A = P @ L @ U`
>
> where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular. If `permute_l` is set to True then L is returned already permuted and hence satisfying `A = L @ U`.

In [1]:
# !pip install numpy scipy

In [2]:
import numpy as np
import scipy.linalg

In [3]:
a = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
p, l, u = scipy.linalg.lu(a)

In [4]:
p @ l @ u

array([[0., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
u

array([[7.        , 8.        , 9.        ],
       [0.        , 2.        , 3.        ],
       [0.        , 0.        , 0.21428571]])

In [6]:
l

array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.57142857, 0.21428571, 1.        ]])

In [7]:
p

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [8]:
l + u - np.eye(3)

array([[7.        , 8.        , 9.        ],
       [0.        , 2.        , 3.        ],
       [0.57142857, 0.21428571, 0.21428571]])

Singularity case

In [9]:
a = [[1,2,3], [2,4,6], [4,5,6]]
p, l, u = scipy.linalg.lu(a)

In [10]:
u

array([[4. , 5. , 6. ],
       [0. , 1.5, 3. ],
       [0. , 0. , 0. ]])

In [11]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

In [12]:
x = scipy.linalg.solve(a, b)

In [13]:
x

array([ 2., -2.,  9.])

In [3]:
import numpy as np

In [6]:
def lu_py(a):
    p = np.arange(len(a))
    for i in range(len(a)):
        pivot_index = np.argmax(np.abs(a[i:, i])) + i
        if pivot_index != i:
            a[[i, pivot_index]] = a[[pivot_index, i]]
            p[[i, pivot_index]] = p[[pivot_index, i]]
        for j in range(i + 1, len(a)):
            a[j, i] /= a[i, i]
            for k in range(i + 1, len(a)):
                a[j, k] -= a[j, i] * a[i, k]
    return a, p

In [7]:
a = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64)
lu_py(a)

(array([[7.        , 8.        , 9.        ],
        [0.        , 2.        , 3.        ],
        [0.57142857, 0.21428571, 0.21428571]]),
 array([2, 0, 1]))