# Linear Solver

## Using LU Decomposition

$A$ is a square matrix, $x$ and $B$ are vectors.

$$
\mathbf{A} x = \mathbf{B}
$$

$A$ can be decomposed into a product of a permutation matrix $P$, a lower triangular matrix $L$ and an upper triangular matrix $U$.

$$
\mathbf{A} = \mathbf{P} \mathbf{L} \mathbf{U}
$$

Then the equation can be rewritten as

$$
\mathbf{P} \mathbf{L} \mathbf{U} x = \mathbf{B}
$$

$x$ can be solved by

$$
x = \mathbf{U}^{-1} \mathbf{L}^{-1} \mathbf{P}^\mathsf{T} \mathbf{B}
$$


In [1]:
# !pip install numpy scipy

In [2]:
import numpy as np
import scipy.linalg

In [3]:
A = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
P, L, U = scipy.linalg.lu(A)

In [4]:
A

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
P@L@U

array([[0., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [6]:
scipy.linalg.inv(A)

array([[-1.        ,  2.        , -1.        ],
       [ 2.        , -7.        ,  4.        ],
       [-1.        ,  4.66666667, -2.66666667]])

In [7]:
scipy.linalg.inv(U) @ scipy.linalg.inv(L) @ P.T

array([[-1.        ,  2.        , -1.        ],
       [ 2.        , -7.        ,  4.        ],
       [-1.        ,  4.66666667, -2.66666667]])

Singularity case

In [11]:
A = [[1,2,3], [2,4,6], [4,5,6]]
P, L, U = scipy.linalg.lu(A)

In [12]:
U

array([[4. , 5. , 6. ],
       [0. , 1.5, 3. ],
       [0. , 0. , 0. ]])

In [13]:
scipy.linalg.inv(U)

LinAlgError: singular matrix